name: rock_paper_scissors_fever
description: Win rock-paper-scissors and get coins.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_neumorphic: ^3.0.3
  rxdart: ^0.24.1
  cupertino_icons: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  flutter_launcher_name: ^0.0.1
flutter_icons:
  android: true
  ios: true
  image_path: "images/app_icon_color.jpg"
flutter_launcher_name:
  name: "RPS Fever"
flutter:
  uses-material-design: true
  assets:
    - images/app_icon_color.jpg
  fonts:
    - family:  RockPaperScissor
      fonts:
        - asset: fonts/RockPaperScissor.ttf

