/// Flutter icons RockPaperScissors
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RockPaperScissors
///      fonts:
///       - asset: fonts/RockPaperScissors.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class RockPaperScissors {
  RockPaperScissors._();

  static const _kFontFam = 'RockPaperScissors';
  static const _kFontPkg = null;

  static const IconData rock =
      IconData(0xf255, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper =
      IconData(0xf256, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scissors =
      IconData(0xf25b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
